version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_server
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    ports:
      - "7000:5432"
    volumes:
      #- postgres_data:/var/lib/postgresql/data
      - ./init-db/init.sql:/docker-entrypoint-initdb.d/init.sql # Mount SQL initialization scripts
#volumes:
# postgres_data:
