version: "3.8"
services:
  postgres_dev:
    image: postgres:latest
    container_name: postgres_dev
    ports:
      - "7000:5432" # Exposing on 5433 for dev
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_database
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:latest
    container_name: postgres_test
    ports:
      - "7001:5432" # Exposing on 5434 for test
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_database
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data:
  postgres_test_data:
