version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_server1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5001:5432"
